config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root "home#index"
  resources :courses do 
    member do
      get 'view_students'
      get 'subscribe_course'
      # get 'un_subscribe_course'
    end
  end

  resources :groups  do 
    member do
      get 'view_students'
      # get 'remove_from_group'
    end
    collection do 
      post 'add_to_group'
    end
  end

  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, format: { with: /\A[a-zA-Z\s]+\z/, message: "Only allow letters" }

  has_and_belongs_to_many :users
end

app/models/courses_users.rb
class CoursesUsers < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, format: { with: /\A[a-zA-Z0-9\s]+\z/, message: "No special characters" }
  
  has_one :project
  has_and_belongs_to_many :users
end

app/models/groups_users.rb
class GroupsUsers < ApplicationRecord
  belongs_to :group
  belongs_to :user
  belongs_to :course

  # self.primary_key = [:id]
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, format: { with: /\A[a-zA-Z0-9\s]+\z/, message: "No special characters" }

  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :login, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: "no special characters allowed" }
  validates :citizen_id, presence: true, uniqueness: true, format: { with: /\A[0-9]+\z/, message: "only allows numbers" }
  validates :role, presence: true
  # validates :student_id, uniqueness: true, format: { with: /\A[0-9]+\z/, message: "only allows numbers" } #uniqueness: true
  # validates :instructor_id, uniqueness: true, format: { with: /\A[0-9]+\z/, message: "only allows numbers" } #uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  enum role: {'Student'=>'Student','Instructor'=>'Instructor','Other'=>'Other'}
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :groups
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  include Pundit

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :citizen_id, :student_id, :instructor_id, :department_name, :login, :role])
    end

    def user_not_authorized
      redirect_to(request.referrer || root_path)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_course, only: [:edit, :update, :view_students]

  def index
    if policy(User).index?
      @courses = Course.where(user_id: current_user.id)
    else
      @courses = current_user.courses
    end
  end

  def new
    @course = current_user.courses.build
  end

  def update
    authorize User
    @course.update(course_params)
    redirect_to courses_path, notice: 'Successfully updated...'
  end

  def create
    authorize User
    @course = Course.new(course_params)
    @course.user_id = current_user.id
    if @course.save
      redirect_to courses_path, notice: 'Successfully Created'
    else
      redirect_to courses_path, notice: 'Error creating course'
    end
  end

  def subscribe_course
    CoursesUsers.create(user_id: current_user.id, course_id: params[:id])
    redirect_to courses_path, notice: 'Successfully Subscribed'
  end

  def view_students
    @students = @course.users
  end

  private
    def find_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :user_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group, only: [:edit, :update]

  def index
    @groups = Group.where(user_id: current_user.id)
    authorize User
  end

  def new
    @group = current_user.groups.build
  end

  def update
    authorize User
    @group.update(group_params)
    redirect_to groups_path, notice: 'Successfully updated...'
  end

  def create
    authorize User
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to groups_path, notice: 'Successfully Created'
    else
      redirect_to groups_path, notice: 'Error creating group'
    end
  end

  def add_to_group
    group_user = GroupsUsers.new(user_id: params[:user_id], group_id: params[:group_id], course_id: params[:course_id])
    if group_user.save
      render json: { msg: 'success', group_name: group_user.group.name }
    else
      render json: { msg: 'failure' }
    end
  end

  private
    def find_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :user_id, :score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @courses = Course.all
    @groups = Group.where(user_id: current_user.id) if current_user.present?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, only: [:edit, :update]

  def index
    @projects = Project.where(user_id: current_user.id)
    authorize User
  end

  def new
    @project = current_user.projects.build
  end

  def update
    authorize User
    @project.update(project_params)
    redirect_to projects_path, notice: 'Successfully updated...'
  end

  def create
    authorize User
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to projects_path, notice: 'Successfully Created'
    else
      redirect_to projects_path, notice: 'Error creating project'
    end
  end

  private
    def find_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :user_id, :group_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: [:edit, :update,:destroy]

  def index
    @users = User.all
    authorize User
  end

  def update
    authorize @user
    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'Successfully updated...'
    else  
      redirect_to users_path, alert: "Unable to update user."
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to users_path, notice: 'Successfully Deleted'
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :login, :student_id, :citizen_id, :department_name, :instructor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.haml
.container
  .row
    .col-4.offset-4.border
      =form_for (@course) do |f|
        .form-group
          =f.label :name
          =f.text_field :name, class: 'form-control'
        .form-group
          =f.submit "Done", class: 'btn btn-success mt-3'

app/views/courses/edit.html.haml
=render 'form'

app/views/courses/index.html.haml
.container
  .row
    .col-10.offset-1
      -if current_user.present? and current_user.role == "Instructor"
        %h2.text-center Courses you have created
      -else
        %h2.text-center Courses you have subscribed
      
      %table.table.table-bordered.table-hover
        %thead.bg-primary.text-white
          %tr
            %th Course Name
            -if current_user.present? and current_user.role == "Instructor"
              %th{colspan: 3} Actions
        %tbody
          -if @courses.present?
            -@courses.each do |course|
              %tr
                %td=course.name
                -if current_user.present? and current_user.role == "Instructor"
                  %td=link_to "Edit", edit_course_path(course)
                  %td=link_to "View Students", view_students_course_path(course)
          -else
            %tr
              %td{colspan: 3}= "No Courses to show"
  .row.float-right
    .col-12
      -if current_user.present? and current_user.role == "Instructor"
        =link_to "Create Course", new_course_path, class: 'btn btn-success mt-5'

app/views/courses/new.html.haml
=render 'form'

app/views/courses/view_students.html.haml
%div.alert.alert-success.hidden
  %span
%h1.text-center.mt-2 Students

=hidden_field_tag :course_id, params[:id]
%table.table.table-bordered.table-hover
  %thead.bg-dark.text-white
    %tr
      %th Student ID
      %th Name
      %th Add to Group
  %tbody
    -@students.each do |student|
      %tr
        %td=student.id
        %td=student.first_name + "  "+student.last_name
        %td=select_tag :group_id, options_for_select(Group.where(user_id: current_user.id).map{ |g| [g.name,g.id]}, GroupsUsers.where(user_id: student.id, course_id: params[:id])[0].try(:group_id)), {include_blank: 'Select Group', class: 'form-control', onchange: 'add_to_group(this)'}

:javascript
  function add_to_group(element){
    var user_id = $(element).closest('tr').find('td:first-child').html();
    var group_id = $(element).val();

    $.ajax({
      type: 'POST',
      url: '/groups/add_to_group',
      data: {'user_id': user_id, 'group_id': group_id, 'course_id': $("#course_id").val()},
      success: function(response){
        $('div.alert').removeClass('hidden');
        $('div.alert').html("User Added To Group");
        $(element).closest('tr').hide();
      },
      error: function(error){

      }
    })
  }

app/views/groups/_form.html.haml
.container
  .row
    .col-4.offset-4.border
      =form_for (@group) do |f|
        .form-group
          =f.label :name
          =f.text_field :name, class: 'form-control'
        -if params[:add_marks] == "true"
          .form-group
            =f.label "Score"
            =f.text_field :score, class: 'form-control'
        .form-group
          =f.submit "Done", class: 'btn btn-success mt-3'

app/views/groups/edit.html.haml
=render 'form'

app/views/groups/index.html.haml
.container
  .row
    .col-10.offset-1
      %h2.text-center Groups you have created
      %table.table.table-bordered.table-hover
        %thead.bg-primary.text-white
          %tr
            %th Group Name
            %th Actions
            %th Marks
        %tbody
          -if @groups.present?
            -@groups.each do |group|
              %tr
                %td=group.name
                %td=link_to "Edit", edit_group_path(group)
                %td= group.score.present? ? group.score : (link_to "Add Marks", edit_group_path(group,add_marks: true))
          -else
            %tr
              %td{colspan: 3}= "No Groups to show"
  .row.float-right
    .col-12
      =link_to "Create Group", new_group_path, class: 'btn btn-success mt-5'

app/views/groups/new.html.haml
=render 'form'

app/views/home/index.html.haml
-if current_user.present? and current_user.role == "Instructor"
  .row
    .col-6.offset-3
      %h2.text-center My Groups Stats
      %table.table.table-bordered.table-hover
        %thead.bg-success.text-white
          %tr
            %th Group Name
            %th Number of Students
        %tbody
          -if @groups.present?
            -@groups.each do |group|
              %tr
                %td=group.name
                %td=group.users.count
-else
  .container
    .row
      .col-6.offset-3
        %h2.text-center All Courses
        .list-group
          -if @courses.present?
            -@courses.each do |course|
              .list-group-item.list-group-item-action{:href => "#"}
                %span=course.name
                -if current_user.present?
                  -if current_user.role == "Student" or current_user.role == "Other"
                    =link_to "Subscribe", subscribe_course_course_path(course), class: 'btn-sm btn btn-success float-right'
          -else
            .list-group-item.list-group-item-action{:href => "#"}
              %span  No Courses Available

app/views/layouts/_top_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  = link_to "Online Course", root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      = link_to "Home", root_path, class: 'nav-item nav-link active'
      = link_to "My Courses", courses_path, class: 'nav-item nav-link active'
      - if current_user.present? and current_user.role == "Instructor"
        = link_to "Groups", groups_path, class: 'nav-item nav-link active'
        = link_to "Projects", projects_path, class: 'nav-item nav-link active'
        = link_to "Users", users_path, class: 'nav-item nav-link active'

    .ul.ml-auto
      - if current_user.present?
        = link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-item nav-link text-white'
      - else
        .row
          = link_to "Login", new_user_session_path, class: 'nav-item nav-link text-white'
          = link_to "Sign up", new_user_registration_path, class: 'nav-item nav-link text-white'
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CourseManagement
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/top_navbar'
    = yield

app/views/projects/_form.html.haml
.container
  .row
    .col-4.offset-4.border
      =form_for (@project) do |f|
        .form-group
          =f.label :name
          =f.text_field :name, class: 'form-control'
        .form-group
          =f.label "Assign to group"
          =f.select :group_id, options_for_select(Group.where(user_id: current_user.id).map{ |p| [p.name, p.id]}, @project.try(:group).try(:id)), {include_blank: 'Assign To Group'},{ class: 'form-control mt-3'}
        .form-group
          =f.submit "Done", class: 'btn btn-success mt-3'

app/views/projects/edit.html.haml
=render 'form'

app/views/projects/index.html.haml
.container
  .row
    .col-10.offset-1
      %h2.text-center Projects you have created
      %table.table.table-bordered.table-hover
        %thead.bg-primary.text-white
          %tr
            %th Project Name
            %th Assigned to Group
            %th{colspan: 2} Actions
        %tbody
          -if @projects.present?
            -@projects.each do |project|
              %tr
                %td=project.name
                %th=project.group.name
                %td=link_to "Edit", edit_project_path(project)
          -else
            %tr
              %td{colspan: 3}= "No Projects to show"
  .row.float-right
    .col-12
      =link_to "Create Project", new_project_path, class: 'btn btn-success mt-5'

app/views/projects/new.html.haml
=render 'form'

app/views/users/_form.html.haml
.row
  .col-4.offset-4.border
    %h2 User Form
    = form_for(@user) do |f|
      .form-group
        = f.label :first_name
        = f.text_field :first_name, class: 'form-control'
      .form-group
        = f.label :last_name
        = f.text_field :last_name, class: 'form-control'
      .form-group
        = f.label "username"
        = f.text_field :login, class: 'form-control'
      .actions
        = f.submit "Update", class: 'btn btn-primary float-right mt-3 mb-3'

app/views/users/edit.html.haml
=render 'form'

app/views/users/index.html.haml
%h1.text-center All Users
%table.table.table-bordered.table-hover
  %thead.bg-primary.text-white
    %tr
      %th Name
      %th Student ID
      %th Instructor ID
      %th Username
      %th Citizen ID
      %th{colspan: 2} Actions
  %tbody
    -if @users.present?
      -@users.each do |user|
        %tr
          %td=user.first_name + " "+ user.last_name
          %th=user.student_id
          %th=user.instructor_id
          %th=user.login
          %th=user.citizen_id
          -if current_user.present? and current_user.role == "Instructor"
            %td=link_to "Edit", edit_user_path(user)
            %td=link_to "Delete", user_path(user), method: :delete
    -else
      %tr
        %td{colspan: 3}= "No Users to show"